### ISSUE TITLE
testing problem

### ISSUE THREAD

**Issue by fahriwp** [sujanay/Classifying-MIAS-database-of-mammogram-images-as-malignant-or-benign#2]
Why testing.py only shows benign prediction? Where's malignant prediction? is it because total images for testing is not enough ?

**Comment by sujanay** [comment]
`def Main():

    test(test_batchsize,            # test batch size
         'FALSE',                         # show_errors
         'TRUE')                          # show_correct_predictions

if __name__ == '__main__':
    Main()`

There is a flag that you can set/change in test.py to see the prediction for benign/malignant.
